### PR TITLE
Complete redux refactoring + some bonus

### PR DESCRIPTION
**Pull request by AymericBethencourt**
- Complete refactor of the Redux actions and reducers to follow best practics
- Removed dispatch from components and replaced them with actions (best practices as well)
- Added support for Redux DevTool Chrome Extension (I suggest you use it ^^)
- Added a manifest and a png icon
- Added a logo in the menu
- Added connected-react-router for tracking route changes in redux
- Added redux-thunk for asynchronous dispatch
- Added a Toastr component with corresponding actions, triggered automatically upon logging in and out.
- Renamed some variables according to clean code conventions
- Tweaked the eslint and vscode config for better linting on import errors

### CODE REVIEW

**Comment by IgorMCesar** [comment]
That's awesome! There are a lot of files to review so i will take sometime, but I already saw some changes that i want to understand more about:

- Why did you make a new toastr if Antd already has one? https://ant.design/components/message/
- Why did you add TypeScript to Readme? I dont't know if we will make this transition in the future. PropTypes are not good enough in your opinion?
-  On Redux, I never saw defaultState instead of initialState, do you have any source to support that 
change?

**Comment by AymericBethencourt** [comment]
- oh I didn't know antd had one, I will remove the one I made and integrate the antd one in my next commit.
- Typescript is much more powerful than simple PropTypes. The ts linter saved my ass many times, for example when trying to assign an object to a string my mistake because I didn't properly destructurated the object. IMO any serious project need to be done is TS rather than JS. Also all JS code is perfectly compatible with TS, they just add some awesome features like types and interfaces, especially since graphql does use these already. However I admit that TS is much less popular than JS and this could discourage some devs to use the boilerplate, so let's remove it but keep it in mind for later.
- You are right regarding defaultState, force of habits, seems like initialState is more standard. Switching it back in my next commit :)

**Comment by AymericBethencourt** [comment]
Done :)

**Comment by IgorMCesar** [comment]
Really sorry to make you wait, I am really busy with work right now. Tonight I will open a PR to your PR, just to make small changes.

**Review by IgorMCesar — APPROVED** [review]
I will merge, but later will make the chages that are: 

- Refactor Toastr message to be a component and decouple it from redux action
- Change Actions and Reducers root file name ( index.js is not a good file name to work with, it's difficult to code if every root is an index.js)
- Wil change the logo to be the same as on readme (but will maintain rocket ico, really liked it =D)

**Comment by IgorMCesar** [comment]
Completed Issues #10 #11

**Pull request merged**
